# Generated by Django 5.0.6 on 2024-06-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
                ('wikipedia_uri', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
